import type { SignalingSocket } from "../signaling";
import {
  authContext,
  createRoomId,
  deriveRoomKey,
  isNonce,
  isRecord,
  randomHex,
  SignedChannel,
  verify,
  usernameError,
  passwordError,
  type Participant,
  type RoutedMedia
} from "../protocol";
import type { StreamQuality } from "../media";
import { RoomSession, type SessionEvents } from "./room-session";
import { Transport, openSignaling } from "./transport";
import { CONNECTION_TIMEOUT } from "./constants";

type Client = {
  transport: Transport;
  timer: ReturnType<typeof setTimeout>;
  info?: Participant;
};

export class HostSession extends RoomSession {
  readonly roomId: string;
  private clients = new Map<string, Client>();

  private constructor(
    socket: SignalingSocket,
    private key: CryptoKey,
    private username: string,
    events: SessionEvents
  ) {
    super(socket, events);
    this.roomId = socket.id;
    socket.onmessage = (from, message) => {
      if (this.closed) return;
      if (!this.clients.has(from)) {
        if (
          !isRecord(message) ||
          message.type !== "hello" ||
          !isNonce(message.nonce)
        )
          return;
        this.accept(from);
      }
      this.clients.get(from)?.transport.receive(message);
    };
    this.signalingState = "ready";
    this.reportDiagnostics();
  }

  static async start(
    password: string,
    username: string,
    source: MediaStream,
    events: SessionEvents,
    quality: StreamQuality = "source"
  ) {
    const issue = passwordError(password) || usernameError(username);
    if (issue) throw new Error(issue);
    const roomId = createRoomId();
    let session: HostSession | undefined;
    try {
      const key = await deriveRoomKey(password, roomId);
      const socket = await openSignaling(roomId, events);
      session = new HostSession(socket, key, username.trim(), events);
      await session.setPublishQuality(quality);
      await session.startSharing(source);
      events.ready();
      return session;
    } catch (error) {
      source.getTracks().forEach((track) => track.stop());
      session?.close();
      throw error;
    }
  }

  protected async announce() {
    if (this.closed) return;
    const participants: Participant[] = [
      { id: this.id, username: this.username, streamId: this.streamId },
      ...Array.from(this.clients.values()).flatMap((client) =>
        client.info ? [client.info] : []
      )
    ];
    // Queue the roster before any media signals generated by its application.
    const sends = Array.from(this.clients.values())
      .filter((client) => client.info)
      .map((client) =>
        client.transport
          .send({ type: "roster", participants })
          .catch(() => this.remove(client.transport.peer))
      );
    this.setRoster(participants);
    await Promise.all(sends);
  }

  protected async route(message: RoutedMedia) {
    if (this.closed) return;
    if (
      !this.participants.some(
        (p) => p.id === message.publisher && p.streamId === message.streamId
      )
    )
      return;
    if (message.publisher !== message.from && message.publisher !== message.to)
      throw new Error("Invalid media route.");
    if (message.to === this.id) await this.receiveMedia(message);
    else {
      const target = this.clients.get(message.to);
      if (target?.info)
        await target.transport
          .send(message)
          .catch(() => this.remove(message.to));
    }
  }

  private remove(id: string) {
    const client = this.clients.get(id);
    if (!client) return;
    this.clients.delete(id);
    clearTimeout(client.timer);
    client.transport.close();
    if (!this.closed) void this.announce();
  }

  private accept(id: string) {
    if (
      this.closed ||
      this.clients.has(id) ||
      this.clients.size >= 255 ||
      !/^viewer-[a-f0-9]{32}$/.test(id) ||
      Array.from(this.clients.values()).filter((client) => !client.info)
        .length >= 32
    )
      return;
    let stage: "hello" | "auth" | "profile" | "ready" | "rejected" = "hello";
    let context = "";
    const remove = () => this.remove(id);
    const transport = new Transport(
      id,
      this.socket,
      async (message) => {
        if (stage === "rejected") return;
        if (!isRecord(message)) throw new Error("Invalid connection message.");
        if (stage === "hello") {
          if (message.type !== "hello" || !isNonce(message.nonce))
            throw new Error("Invalid greeting.");
          const nonce = randomHex();
          context = authContext(this.roomId, id, message.nonce, nonce);
          stage = "auth";
          transport.raw({ type: "challenge", nonce });
        } else if (stage === "auth") {
          if (
            message.type !== "auth" ||
            !(await verify(this.key, `${context}:join`, message.proof))
          ) {
            stage = "rejected";
            transport.raw({ type: "rejected" });
            remove();
            return;
          }
          if (transport.closed || this.closed) return;
          transport.channel = new SignedChannel(this.key, context, "host");
          stage = "profile";
        } else {
          const signal = await transport.channel!.unpack(message);
          if (transport.closed || this.closed) return;
          const client = this.clients.get(id)!;
          if (stage === "profile") {
            if (signal.type !== "profile")
              throw new Error("Username required.");
            client.info = {
              id,
              username: signal.username.trim(),
              streamId: null
            };
            clearTimeout(client.timer);
            stage = "ready";
            transport.startHeartbeat();
            await this.announce();
          } else if (await transport.control(signal)) return;
          else if (signal.type === "publish") {
            client.info!.streamId = signal.streamId;
            await this.announce();
          } else if (signal.type === "media") {
            if (signal.from !== id) throw new Error("Invalid sender.");
            await this.route(signal);
          } else if (signal.type === "ended") remove();
          else throw new Error("Unexpected session message.");
        }
      },
      remove
    );
    this.clients.set(id, {
      transport,
      timer: setTimeout(remove, CONNECTION_TIMEOUT)
    });
  }

  private async end() {
    if (this.closed) return;
    this.cleanup();
    const clients = Array.from(this.clients.values());
    clients.forEach((client) => clearTimeout(client.timer));
    await Promise.allSettled(
      clients
        .filter((client) => client.info)
        .map((client) => client.transport.send({ type: "ended" }))
    );
    clients.forEach((client) => client.transport.close());
    this.clients.clear();
    this.socket.close();
  }
  close() {
    void this.end();
  }
}
